flowchart TD

%% 要素
    User(ユーザー)
    Post(記事)
    Comment(コメント)
    Category(カテゴリー)
    Recommend(いいね)

%% 連関
    User -- wrote --> Post
    Recommend -- by --> User
    Post -- have --> Recommend
    Post -- written by --> User
    Post -- have --> Comment
    Post -- have --> Category
    Comment -- written by --> User

    style User fill:#d0b6eb;
    style Post fill:#d0b6eb;
    style Comment fill:#d0b6eb;


    linkStyle 3 stroke-width:3px, stroke:purple;
    linkStyle 4 stroke-width:3px, stroke:purple;
    linkStyle 6 stroke-width:3px, stroke:purple;
